version: '3'
services:
  frontend:
    build:
      context: ./client/.
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/client
      - /client/node_modules
  backend:
    build: ./server/.
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/code
